
var getHostForGlobal = function (api) {
    var hosts = {
        "$3EC_HOST": "http://workbench.yyuap.com",
        "$MFGED_HOST": "http://ysed-test.yyuap.com",
        "": "",
        "$YHT_ASSIST": "",
        "$SDMA_HOST": "http://u8cmallserver-test.yyuap.com",
        "$VIP_HOST": "http://u8cvip-test.yyuap.com",
        "$AUTH_HOST": "http://u8c-auth-test.yyuap.com",
        "$USTOCK_HOST": "http://u8custock-test.yyuap.com",
        "$ORG_HOST": "http://ucf-orgcenter-fe.test.app.yyuap.com",
        "$XY_RPA__HOST": "",
        "$SCMSA_HOST": "http://u8csa-test.yyuap.com",
        "$BD_HOST": "http://ucf-staff-center-fe.test.app.yyuap.com",
        "$MZ_HOST": "",
        "$OPEN_HOST": "",
        "$MS_HOST": "https://ms.yyuap.com",
        "$EZONE_HOST": "http://ezone.chaoke.com:6058",
        "$BD_ORG_STAFF_HOST": "",
        "$UPC_HOST": "http://u8cupc-test.yyuap.com",        // 向导
        "$PRINT_HOST": "http://u8cprint.test.app.yyuap.com",
        "$ICC_HOST": "http://u8cicc-test.yyuap.com",
        "$YHT_USER": "",
        "$HR_HOST": "http://hrcloud.yyuap.com",             // 员工信息
        "$DIWORK_WORKBENCH_HOST": "",
        "$yb": "http://yb91.yyuap.com:91",
        "$RPA_HOST": "",
        "$PUBACCOUNT_HOST": "",
        "$VPA_HOST": "http://vpa-manage-fe.test.app.yyuap.com",
        "$YS_HOST": "http://ys91.yyuap.com:91",
        "$DIWORK_MS_YM_HOST": "",
        "$DIWORK_STAFF_HOST": "",
        "$FINBD_HOST": "",
        "$NEC_HOST": "http://web.yyuap.com:91",         //空间管理，门户
        "$UCF_HOST": "http://ucfbasedoc-fe.test.app.yyuap.com",
        "$ubl": "http://ubl.yyuap.com",
        "$YB_HOST": "http://yb91.yyuap.com:91",
        "$VPA_FE_HOST": "",
        "$DIWORK_UBL_HOST": "",
        "$ACC_HOST": "http://u8cacc-test.yyuap.com",
        "$SCMSA_META_HOST": "http://u8c3-bill-node.test.app.yyuap.com",
        "$YHT_APPTENANT": "",
        "$YHT_ENTERPRISE": "",
        "$EXT_BACK_HOST": "http://u8c-ext.test.app.yyuap.com",
        "$PM_CLOUD": "",
        "$TPL_HOST": "http://u8cmanage.test.app.yyuap.com",
        "$ezone": "http://ezone.chaoke.com:6058",
        "$EXT_HOST": "http://u8cdev-ext-fe.test.app.yyuap.com",
        "$IDTEST_HOST": "https://idtest.yyuap.com",         // 登录
        "$WORKBENCH_HOST": "http://workbench.yyuap.com",
        "$DIWORK_ORG_HOST": "", "$DIWORK_MS_HOST": "",
        "$BASE_MC_HOST": "http://u8c-mc.test.app.yyuap.com",
        "$MFGMR_HOST": "http://ysmr-test.yyuap.com",
        "$YHT_SSO": "",
        "$EC_HOST": "http://web.yyuap.com:91",
        "$YBZ_HOST": "http://u8cybz-test.yyuap.com",
        "$MSG_HOST": "http://iuap-message-platform-fe.test.app.yyuap.com",
        "$YHT_MANAGER": "",
        "$UPC_SERVER_HOST": "http://upc-server.test.app.yyuap.com",
        "$REPORT_HOST": "http://v.yyuap.com",
        "$CONFIG_HOST": "http://u8c-config-test.yyuap.com",
        "$DIWORK_BD_HOST": "",
        "$DIWORK_PRINT_HOST/": "",
        "$MFGPO_HOST": "http://yspo-test.yyuap.com",
        "$UCFBASEDOC_HOST": "http://ucfbasedoc.test.app.yyuap.com",
        "$YC_HOST": "http://u8cpur-test.yyuap.com",
        "$ybz": "http://ybz.yyuap.com"
    };
    return hosts[api];
}